azure:
  keyvault:
    enabled: true
    uri: https://projcond.vault.azure.net/
    client-id: 22e53919-d8d5-47b0-8112-9a91b9328f9a
    client-key: 1R68Q~qJcQFBfoNa4BGn4GYT2AGKv7wFtFgVxcn.
    tenant-id: e4345e91-37e0-4df4-84e5-f4cd08735abc

